mutation AddOrder(
  $orderId: String
  $posted: Boolean
  $orderDate: String
  $customerId: String
  $customerFirstName: String
  $customerLastName: String
  $customerEmail: String
  $quantity: Int
  $productId: String
  $productName: String
  $productUrl: String
) {
  addOrder(
    orderId: $orderId
    posted: $posted
    orderDate: $orderDate
    customerId: $customerId
    customerFirstName: $customerFirstName
    customerLastName: $customerLastName
    customerEmail: $customerEmail
    quantity: $quantity
    productId: $productId
    productName: $productName
    productUrl: $productUrl
  )
}
