query GetOrders {
  getOrders {
    id
    orderId
    posted
    orderDate
    customerId
    customerFirstName
    customerLastName
    customerEmail
    quantity
    productId
    productName
    productUrl
  }
}
